name: Settings
type: SettingsMenu
children:
  - name: MasterLabel
    type: Label
    Position: [100, 100]
    HorizontalAlignment: Right
    Text: Master
    Theme:
        Font: Res/Fonts/RaceSport.ttf:16
    children:
      - name: Slider
        type: HSlider
        HorizontalAlignment: Left
        Position: [32,-8]

  - name: MusicLabel
    type: Label
    Position: [100,150]
    HorizontalAlignment: Right
    Text: Music
    Theme:
        Font: Res/Fonts/RaceSport.ttf:16
    children:
      - name: Slider
        type: HSlider
        HorizontalAlignment: Left
        Position: [32,-8]

  - name: SfxLabel
    type: Label
    Position: [100,200]
    HorizontalAlignment: Right
    Text: SFX
    Theme:
        Font: Res/Fonts/RaceSport.ttf:16
    children:
      - name: Slider
        type: HSlider
        Position: [32,-8]
        HorizontalAlignment: Left

  - name: ApplyButton
    type: Button
    Text: Apply
    FocusNeighborLeft: ../ReturnButton
    FocusNeighborRight: ../ReturnButton
    ThemeFile: Res/Themes/Button.theme.yaml

  - name: ReturnButton
    type: Button
    Text: Return
    FocusNeighborLeft: ../ApplyButton
    FocusNeighborRight: ../ApplyButton
    ThemeFile: Res/Themes/Button.theme.yaml