name: Settings
type: SettingsMenu
#masterLabel: MasterLabel
#musicLabel: MusicLabel
#sfxLabel: SfxLabel
#masterSlider: MasterLabel/Slider
#musicSlider: MusicLabel/Slider
#sfxSlider: SfxLabel/Slider
#applyButton: ApplyButton
#returnButton: ReturnButton
children:

  - name: MasterLabel
    type: Label
    #HorizontalAlignment: Right
    Text: Master
    #Theme:
        #Font: Res/Fonts/RaceSport.ttf:16
    children:
      - name: Slider
        type: HSlider
        path: Res/Scenes/Slider.yaml
        #HorizontalAlignment: Left
        FocusNeighborTop: ../../ReturnButton
        FocusNeighborBottom: ../../MusicLabel/Slider

  - name: MusicLabel
    type: Label
    #HorizontalAlignment: Right
    Text: Music
    #Theme:
        #Font: Res/Fonts/RaceSport.ttf:16
    children:
      - name: Slider
        type: HSlider
        path: Res/Scenes/Slider.yaml
        FocusNeighborTop: ../../MasterLabel/Slider
        FocusNeighborBottom: ../../SfxLabel/Slider

  - name: SfxLabel
    type: Label
    #HorizontalAlignment: Right
    Text: SFX
    #Theme:
        #Font: Res/Fonts/RaceSport.ttf:16
    children:
      - name: Slider
        type: HSlider
        path: Res/Scenes/Slider.yaml
        FocusNeighborTop: ../../MusicLabel/Slider
        FocusNeighborBottom: ../../ReturnButton

  - name: ApplyButton
    type: Button
    path: Res/Scenes/Button.yaml
    Text: Apply
    FocusNeighborLeft: ../ReturnButton
    FocusNeighborTop: ../SfxLabel/Slider
    FocusNeighborRight: ../ReturnButton

  - name: ReturnButton
    type: Button
    path: Res/Scenes/Button.yaml
    Text: Return
    FocusNeighborLeft: ../ApplyButton
    FocusNeighborTop: ../SfxLabel/Slider
    FocusNeighborBottom: ../MasterLabel/Slider
    FocusNeighborRight: ../ApplyButton